export interface ContractType {
  id: string;
  title: string;
  description: string;
  category: 'sale' | 'rental' | 'service' | 'donation' | 'loan' | 'other';
  fields: FormField[];
}

export interface FormField {
  name: string;
  label: string;
  type: 'text' | 'email' | 'tel' | 'number' | 'select' | 'textarea' | 'date' | 'cpf' | 'cnpj' | 'currency';
  required: boolean;
  options?: string[];
  placeholder?: string;
  validation?: {
    min?: number;
    max?: number;
    pattern?: string;
  };
}

export const contractTypes: ContractType[] = [
  {
    id: 'compra-venda',
    title: 'Contrato de Compra e Venda',
    description: 'Transferência de bens (imóveis, veículos, móveis, etc.)',
    category: 'sale',
    fields: [
      { name: 'vendedor_nome', label: 'Nome do Vendedor', type: 'text', required: true },
      { name: 'vendedor_cpf', label: 'CPF do Vendedor', type: 'cpf', required: true },
      { name: 'vendedor_rg', label: 'RG do Vendedor', type: 'text', required: true },
      { name: 'vendedor_estado_civil', label: 'Estado Civil do Vendedor', type: 'select', required: true, options: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
      { name: 'vendedor_endereco', label: 'Endereço do Vendedor (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'vendedor_numero', label: 'Número', type: 'text', required: true },
      { name: 'vendedor_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'vendedor_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'vendedor_estado', label: 'Estado', type: 'text', required: true },
      { name: 'vendedor_cep', label: 'CEP', type: 'text', required: true },
      { name: 'vendedor_email', label: 'E-mail do Vendedor', type: 'email', required: true },
      { name: 'vendedor_whatsapp', label: 'WhatsApp do Vendedor', type: 'tel', required: true },
      { name: 'comprador_nome', label: 'Nome do Comprador', type: 'text', required: true },
      { name: 'comprador_cpf', label: 'CPF do Comprador', type: 'cpf', required: true },
      { name: 'comprador_rg', label: 'RG do Comprador', type: 'text', required: true },
      { name: 'comprador_estado_civil', label: 'Estado Civil do Comprador', type: 'select', required: true, options: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
      { name: 'comprador_endereco', label: 'Endereço do Comprador (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'comprador_numero', label: 'Número', type: 'text', required: true },
      { name: 'comprador_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'comprador_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'comprador_estado', label: 'Estado', type: 'text', required: true },
      { name: 'comprador_cep', label: 'CEP', type: 'text', required: true },
      { name: 'comprador_email', label: 'E-mail do Comprador', type: 'email', required: true },
      { name: 'comprador_whatsapp', label: 'WhatsApp do Comprador', type: 'tel', required: true },
      { name: 'bem_descricao', label: 'Descrição do Bem', type: 'textarea', required: true, placeholder: 'Ex: Apartamento localizado na Rua..., Veículo modelo...' },
      { name: 'valor_venda', label: 'Valor da Venda', type: 'currency', required: true },
      { name: 'forma_pagamento', label: 'Forma de Pagamento', type: 'select', required: true, options: ['À vista', 'Parcelado em 2x', 'Parcelado em 3x', 'Parcelado em 6x', 'Parcelado em 12x', 'Financiamento bancário'] },
      { name: 'data_entrega', label: 'Data de Entrega do Bem', type: 'date', required: true },
    ]
  },
  {
    id: 'locacao-residencial',
    title: 'Contrato de Locação Residencial',
    description: 'Aluguel de casa, apartamento, quitinete',
    category: 'rental',
    fields: [
      { name: 'locador_nome', label: 'Nome do Locador', type: 'text', required: true },
      { name: 'locador_cpf', label: 'CPF do Locador', type: 'cpf', required: true },
      { name: 'locador_rg', label: 'RG do Locador', type: 'text', required: true },
      { name: 'locador_endereco', label: 'Endereço do Locador (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'locador_numero', label: 'Número', type: 'text', required: true },
      { name: 'locador_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'locador_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'locador_estado', label: 'Estado', type: 'text', required: true },
      { name: 'locador_cep', label: 'CEP', type: 'text', required: true },
      { name: 'locador_email', label: 'E-mail do Locador', type: 'email', required: true },
      { name: 'locador_whatsapp', label: 'WhatsApp do Locador', type: 'tel', required: true },
      { name: 'locatario_nome', label: 'Nome do Locatário', type: 'text', required: true },
      { name: 'locatario_cpf', label: 'CPF do Locatário', type: 'cpf', required: true },
      { name: 'locatario_rg', label: 'RG do Locatário', type: 'text', required: true },
      { name: 'locatario_endereco', label: 'Endereço do Locatário (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'locatario_numero', label: 'Número', type: 'text', required: true },
      { name: 'locatario_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'locatario_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'locatario_estado', label: 'Estado', type: 'text', required: true },
      { name: 'locatario_cep', label: 'CEP', type: 'text', required: true },
      { name: 'locatario_email', label: 'E-mail do Locatário', type: 'email', required: true },
      { name: 'locatario_whatsapp', label: 'WhatsApp do Locatário', type: 'tel', required: true },
      { name: 'imovel_endereco', label: 'Endereço do Imóvel (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'imovel_numero', label: 'Número do Imóvel', type: 'text', required: true },
      { name: 'imovel_bairro', label: 'Bairro do Imóvel', type: 'text', required: true },
      { name: 'imovel_cidade', label: 'Cidade do Imóvel', type: 'text', required: true },
      { name: 'imovel_estado', label: 'Estado do Imóvel', type: 'text', required: true },
      { name: 'imovel_cep', label: 'CEP do Imóvel', type: 'text', required: true },
      { name: 'valor_aluguel', label: 'Valor do Aluguel', type: 'currency', required: true },
      { name: 'prazo_contrato', label: 'Prazo do Contrato (meses)', type: 'number', required: true, validation: { min: 1, max: 60 } },
      { name: 'reajuste', label: 'Índice de Reajuste', type: 'select', required: true, options: ['IGP-M', 'IPCA', 'INCC', 'Sem reajuste'] },
      { name: 'caucao', label: 'Valor da Caução', type: 'currency', required: false },
      { name: 'fiador_nome', label: 'Nome do Fiador (opcional)', type: 'text', required: false },
      { name: 'fiador_cpf', label: 'CPF do Fiador (opcional)', type: 'cpf', required: false },
      { name: 'fiador_rg', label: 'RG do Fiador (opcional)', type: 'text', required: false },
      { name: 'fiador_endereco', label: 'Endereço do Fiador (Rua/Av/Rod)', type: 'text', required: false },
      { name: 'fiador_numero', label: 'Número', type: 'text', required: false },
      { name: 'fiador_bairro', label: 'Bairro', type: 'text', required: false },
      { name: 'fiador_cidade', label: 'Cidade', type: 'text', required: false },
      { name: 'fiador_estado', label: 'Estado', type: 'text', required: false },
      { name: 'fiador_cep', label: 'CEP', type: 'text', required: false },
      { name: 'fiador_email', label: 'E-mail do Fiador (opcional)', type: 'email', required: false },
      { name: 'fiador_whatsapp', label: 'WhatsApp do Fiador (opcional)', type: 'tel', required: false },
    ]
  },
  {
    id: 'locacao-comercial',
    title: 'Contrato de Locação Comercial',
    description: 'Aluguel de imóvel para atividade empresarial',
    category: 'rental',
    fields: [
      { name: 'locador_nome', label: 'Nome/Razão Social do Locador', type: 'text', required: true },
      { name: 'locador_documento', label: 'CPF/CNPJ do Locador', type: 'text', required: true },
      { name: 'locador_rg', label: 'RG do Locador (se pessoa física)', type: 'text', required: false },
      { name: 'locador_endereco', label: 'Endereço do Locador (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'locador_numero', label: 'Número', type: 'text', required: true },
      { name: 'locador_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'locador_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'locador_estado', label: 'Estado', type: 'text', required: true },
      { name: 'locador_cep', label: 'CEP', type: 'text', required: true },
      { name: 'locador_email', label: 'E-mail do Locador', type: 'email', required: true },
      { name: 'locador_whatsapp', label: 'WhatsApp do Locador', type: 'tel', required: true },
      { name: 'locatario_nome', label: 'Nome/Razão Social do Locatário', type: 'text', required: true },
      { name: 'locatario_documento', label: 'CPF/CNPJ do Locatário', type: 'text', required: true },
      { name: 'locatario_rg', label: 'RG do Locatário (se pessoa física)', type: 'text', required: false },
      { name: 'locatario_endereco', label: 'Endereço do Locatário (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'locatario_numero', label: 'Número', type: 'text', required: true },
      { name: 'locatario_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'locatario_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'locatario_estado', label: 'Estado', type: 'text', required: true },
      { name: 'locatario_cep', label: 'CEP', type: 'text', required: true },
      { name: 'locatario_email', label: 'E-mail do Locatário', type: 'email', required: true },
      { name: 'locatario_whatsapp', label: 'WhatsApp do Locatário', type: 'tel', required: true },
      { name: 'imovel_endereco', label: 'Endereço do Imóvel', type: 'textarea', required: true },
      { name: 'finalidade_uso', label: 'Finalidade do Uso', type: 'select', required: true, options: ['Comércio', 'Escritório', 'Consultório', 'Salão', 'Loja', 'Outro'] },
      { name: 'valor_aluguel', label: 'Valor do Aluguel', type: 'currency', required: true },
      { name: 'prazo_contrato', label: 'Prazo do Contrato (meses)', type: 'number', required: true },
      { name: 'iptu_responsavel', label: 'IPTU por conta de', type: 'select', required: true, options: ['Locador', 'Locatário'] },
      { name: 'condominio_responsavel', label: 'Condomínio por conta de', type: 'select', required: true, options: ['Locador', 'Locatário'] },
    ]
  },
  {
    id: 'prestacao-servicos',
    title: 'Contrato de Prestação de Serviços',
    description: 'Contratação de profissionais autônomos',
    category: 'service',
    fields: [
      { name: 'contratante_nome', label: 'Nome do Contratante', type: 'text', required: true },
      { name: 'contratante_documento', label: 'CPF/CNPJ do Contratante', type: 'text', required: true },
      { name: 'contratante_rg', label: 'RG do Contratante (se pessoa física)', type: 'text', required: false },
      { name: 'contratante_endereco', label: 'Endereço do Contratante (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'contratante_numero', label: 'Número', type: 'text', required: true },
      { name: 'contratante_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'contratante_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'contratante_estado', label: 'Estado', type: 'text', required: true },
      { name: 'contratante_cep', label: 'CEP', type: 'text', required: true },
      { name: 'contratante_email', label: 'E-mail do Contratante', type: 'email', required: true },
      { name: 'contratante_whatsapp', label: 'WhatsApp do Contratante', type: 'tel', required: true },
      { name: 'prestador_nome', label: 'Nome do Prestador', type: 'text', required: true },
      { name: 'prestador_cpf', label: 'CPF do Prestador', type: 'cpf', required: true },
      { name: 'prestador_rg', label: 'RG do Prestador', type: 'text', required: true },
      { name: 'prestador_endereco', label: 'Endereço do Prestador (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'prestador_numero', label: 'Número', type: 'text', required: true },
      { name: 'prestador_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'prestador_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'prestador_estado', label: 'Estado', type: 'text', required: true },
      { name: 'prestador_cep', label: 'CEP', type: 'text', required: true },
      { name: 'prestador_email', label: 'E-mail do Prestador', type: 'email', required: true },
      { name: 'prestador_whatsapp', label: 'WhatsApp do Prestador', type: 'tel', required: true },
      { name: 'servicos_descricao', label: 'Descrição dos Serviços', type: 'textarea', required: true },
      { name: 'prazo_execucao', label: 'Prazo de Execução', type: 'text', required: true, placeholder: 'Ex: 30 dias, 2 semanas' },
      { name: 'valor_servico', label: 'Valor do Serviço', type: 'currency', required: true },
      { name: 'forma_pagamento', label: 'Forma de Pagamento', type: 'select', required: true, options: ['À vista', 'Parcelado', '50% início + 50% final', 'Mensal'] },
      { name: 'confidencialidade', label: 'Cláusula de Confidencialidade', type: 'select', required: false, options: ['Sim', 'Não'] },
    ]
  },
  {
    id: 'compra-venda-veiculo',
    title: 'Contrato de Compra e Venda de Veículo',
    description: 'Transferência de propriedade de veículos automotores',
    category: 'sale',
    fields: [
      { name: 'vendedor_nome', label: 'Nome do Vendedor', type: 'text', required: true },
      { name: 'vendedor_cpf', label: 'CPF do Vendedor', type: 'cpf', required: true },
      { name: 'vendedor_rg', label: 'RG do Vendedor', type: 'text', required: true },
      { name: 'vendedor_estado_civil', label: 'Estado Civil do Vendedor', type: 'select', required: true, options: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
      { name: 'vendedor_endereco', label: 'Endereço do Vendedor (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'vendedor_numero', label: 'Número', type: 'text', required: true },
      { name: 'vendedor_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'vendedor_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'vendedor_estado', label: 'Estado', type: 'text', required: true },
      { name: 'vendedor_cep', label: 'CEP', type: 'text', required: true },
      { name: 'vendedor_email', label: 'E-mail do Vendedor', type: 'email', required: true },
      { name: 'vendedor_whatsapp', label: 'WhatsApp do Vendedor', type: 'tel', required: true },
      { name: 'comprador_nome', label: 'Nome do Comprador', type: 'text', required: true },
      { name: 'comprador_cpf', label: 'CPF do Comprador', type: 'cpf', required: true },
      { name: 'comprador_rg', label: 'RG do Comprador', type: 'text', required: true },
      { name: 'comprador_estado_civil', label: 'Estado Civil do Comprador', type: 'select', required: true, options: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
      { name: 'comprador_endereco', label: 'Endereço do Comprador (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'comprador_numero', label: 'Número', type: 'text', required: true },
      { name: 'comprador_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'comprador_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'comprador_estado', label: 'Estado', type: 'text', required: true },
      { name: 'comprador_cep', label: 'CEP', type: 'text', required: true },
      { name: 'comprador_email', label: 'E-mail do Comprador', type: 'email', required: true },
      { name: 'comprador_whatsapp', label: 'WhatsApp do Comprador', type: 'tel', required: true },
      { name: 'veiculo_tipo', label: 'Tipo de Veículo', type: 'select', required: true, options: ['Automóvel', 'Motocicleta', 'Caminhão', 'Ônibus', 'Van', 'Caminhonete', 'Outro'] },
      { name: 'veiculo_marca', label: 'Marca', type: 'text', required: true },
      { name: 'veiculo_modelo', label: 'Modelo', type: 'text', required: true },
      { name: 'veiculo_ano_fabricacao', label: 'Ano de Fabricação', type: 'number', required: true },
      { name: 'veiculo_ano_modelo', label: 'Ano do Modelo', type: 'number', required: true },
      { name: 'veiculo_cor', label: 'Cor', type: 'text', required: true },
      { name: 'veiculo_placa', label: 'Placa', type: 'text', required: true },
      { name: 'veiculo_chassi', label: 'Número do Chassi', type: 'text', required: true },
      { name: 'veiculo_renavam', label: 'RENAVAM', type: 'text', required: true },
      { name: 'veiculo_combustivel', label: 'Combustível', type: 'select', required: true, options: ['Gasolina', 'Etanol', 'Flex', 'Diesel', 'GNV', 'Elétrico', 'Híbrido'] },
      { name: 'veiculo_km', label: 'Quilometragem', type: 'number', required: true },
      { name: 'valor_venda', label: 'Valor da Venda', type: 'currency', required: true },
      { name: 'forma_pagamento', label: 'Forma de Pagamento', type: 'select', required: true, options: ['À vista', 'Parcelado em 2x', 'Parcelado em 3x', 'Parcelado em 6x', 'Parcelado em 12x', 'Financiamento bancário'] },
      { name: 'multas_pendentes', label: 'Possui Multas Pendentes?', type: 'select', required: true, options: ['Não', 'Sim'] },
      { name: 'ipva_quitado', label: 'IPVA Quitado?', type: 'select', required: true, options: ['Sim', 'Não'] },
      { name: 'observacoes', label: 'Observações Adicionais', type: 'textarea', required: false, placeholder: 'Ex: Veículo com manual, 2 chaves, revisões em dia, etc.' },
    ]
  },
  {
    id: 'doacao',
    title: 'Contrato de Doação',
    description: 'Transferência gratuita de bens entre pessoas',
    category: 'donation',
    fields: [
      { name: 'doador_nome', label: 'Nome do Doador', type: 'text', required: true },
      { name: 'doador_cpf', label: 'CPF do Doador', type: 'cpf', required: true },
      { name: 'doador_rg', label: 'RG do Doador', type: 'text', required: true },
      { name: 'doador_estado_civil', label: 'Estado Civil do Doador', type: 'select', required: true, options: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
      { name: 'doador_endereco', label: 'Endereço do Doador (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'doador_numero', label: 'Número', type: 'text', required: true },
      { name: 'doador_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'doador_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'doador_estado', label: 'Estado', type: 'text', required: true },
      { name: 'doador_cep', label: 'CEP', type: 'text', required: true },
      { name: 'doador_email', label: 'E-mail do Doador', type: 'email', required: true },
      { name: 'doador_whatsapp', label: 'WhatsApp do Doador', type: 'tel', required: true },
      { name: 'donatario_nome', label: 'Nome do Donatário', type: 'text', required: true },
      { name: 'donatario_cpf', label: 'CPF do Donatário', type: 'cpf', required: true },
      { name: 'donatario_rg', label: 'RG do Donatário', type: 'text', required: true },
      { name: 'donatario_estado_civil', label: 'Estado Civil do Donatário', type: 'select', required: true, options: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
      { name: 'donatario_endereco', label: 'Endereço do Donatário (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'donatario_numero', label: 'Número', type: 'text', required: true },
      { name: 'donatario_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'donatario_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'donatario_estado', label: 'Estado', type: 'text', required: true },
      { name: 'donatario_cep', label: 'CEP', type: 'text', required: true },
      { name: 'donatario_email', label: 'E-mail do Donatário', type: 'email', required: true },
      { name: 'donatario_whatsapp', label: 'WhatsApp do Donatário', type: 'tel', required: true },
      { name: 'bem_tipo', label: 'Tipo do Bem', type: 'select', required: true, options: ['Imóvel', 'Veículo', 'Dinheiro', 'Móveis', 'Ações/Cotas', 'Outro'] },
      { name: 'bem_descricao', label: 'Descrição Completa do Bem Doado', type: 'textarea', required: true, placeholder: 'Descreva detalhadamente o bem que está sendo doado' },
      { name: 'valor_estimado', label: 'Valor Estimado do Bem', type: 'currency', required: true },
      { name: 'tipo_doacao', label: 'Tipo de Doação', type: 'select', required: true, options: ['Pura e Simples', 'Com Encargo', 'Condicional'] },
      { name: 'encargos', label: 'Descrição dos Encargos (se houver)', type: 'textarea', required: false },
      { name: 'condicoes', label: 'Descrição das Condições (se houver)', type: 'textarea', required: false },
      { name: 'reserva_usufruto', label: 'Reservar Usufruto Vitalício?', type: 'select', required: false, options: ['Não', 'Sim'] },
      { name: 'clausula_reversao', label: 'Cláusula de Reversão?', type: 'select', required: false, options: ['Não', 'Sim'] },
    ]
  },
  {
    id: 'emprestimo',
    title: 'Contrato de Empréstimo entre Pessoas',
    description: 'Empréstimo de dinheiro entre amigos, familiares ou terceiros',
    category: 'loan',
    fields: [
      { name: 'credor_nome', label: 'Nome do Credor', type: 'text', required: true },
      { name: 'credor_cpf', label: 'CPF do Credor', type: 'cpf', required: true },
      { name: 'credor_endereco', label: 'Endereço do Credor', type: 'textarea', required: true },
      { name: 'devedor_nome', label: 'Nome do Devedor', type: 'text', required: true },
      { name: 'devedor_cpf', label: 'CPF do Devedor', type: 'cpf', required: true },
      { name: 'devedor_endereco', label: 'Endereço do Devedor', type: 'textarea', required: true },
      { name: 'valor_emprestimo', label: 'Valor do Empréstimo', type: 'currency', required: true },
      { name: 'juros', label: 'Taxa de Juros (% ao mês)', type: 'number', required: false, validation: { min: 0, max: 12 } },
      { name: 'prazo_pagamento', label: 'Prazo Final para Pagamento', type: 'date', required: true },
      { name: 'forma_pagamento', label: 'Forma de Pagamento', type: 'select', required: true, options: ['À vista', 'Parcelado mensal', 'Parcela única no final'] },
    ]
  },
  {
    id: 'comodato',
    title: 'Contrato de Comodato',
    description: 'Empréstimo gratuito de bem para uso',
    category: 'loan',
    fields: [
      { name: 'comodante_nome', label: 'Nome do Comodante', type: 'text', required: true },
      { name: 'comodante_cpf', label: 'CPF do Comodante', type: 'cpf', required: true },
      { name: 'comodatario_nome', label: 'Nome do Comodatário', type: 'text', required: true },
      { name: 'comodatario_cpf', label: 'CPF do Comodatário', type: 'cpf', required: true },
      { name: 'bem_descricao', label: 'Descrição do Bem Emprestado', type: 'textarea', required: true },
      { name: 'prazo_uso', label: 'Prazo de Uso', type: 'text', required: true, placeholder: 'Ex: 6 meses, 1 ano' },
      { name: 'finalidade_uso', label: 'Finalidade do Uso', type: 'text', required: true },
    ]
  },
  {
    id: 'trabalho-autonomo',
    title: 'Contrato de Trabalho Autônomo',
    description: 'Prestação de serviços autônomos sem vínculo empregatício',
    category: 'service',
    fields: [
      { name: 'contratante_nome', label: 'Nome/Razão Social do Contratante', type: 'text', required: true },
      { name: 'contratante_documento', label: 'CPF/CNPJ do Contratante', type: 'text', required: true },
      { name: 'contratante_rg', label: 'RG do Contratante (se pessoa física)', type: 'text', required: false },
      { name: 'contratante_endereco', label: 'Endereço do Contratante (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'contratante_numero', label: 'Número', type: 'text', required: true },
      { name: 'contratante_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'contratante_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'contratante_estado', label: 'Estado', type: 'text', required: true },
      { name: 'contratante_cep', label: 'CEP', type: 'text', required: true },
      { name: 'contratante_email', label: 'E-mail do Contratante', type: 'email', required: true },
      { name: 'contratante_whatsapp', label: 'WhatsApp do Contratante', type: 'tel', required: true },
      { name: 'autonomo_nome', label: 'Nome do Profissional Autônomo', type: 'text', required: true },
      { name: 'autonomo_cpf', label: 'CPF do Autônomo', type: 'cpf', required: true },
      { name: 'autonomo_rg', label: 'RG do Autônomo', type: 'text', required: true },
      { name: 'autonomo_profissao', label: 'Profissão/Atividade', type: 'text', required: true },
      { name: 'autonomo_endereco', label: 'Endereço do Autônomo (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'autonomo_numero', label: 'Número', type: 'text', required: true },
      { name: 'autonomo_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'autonomo_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'autonomo_estado', label: 'Estado', type: 'text', required: true },
      { name: 'autonomo_cep', label: 'CEP', type: 'text', required: true },
      { name: 'autonomo_email', label: 'E-mail do Autônomo', type: 'email', required: true },
      { name: 'autonomo_whatsapp', label: 'WhatsApp do Autônomo', type: 'tel', required: true },
      { name: 'servicos_descricao', label: 'Descrição dos Serviços', type: 'textarea', required: true, placeholder: 'Descreva detalhadamente os serviços a serem prestados' },
      { name: 'prazo_execucao', label: 'Prazo de Execução', type: 'text', required: true, placeholder: 'Ex: 30 dias, 3 meses, 1 ano' },
      { name: 'local_execucao', label: 'Local de Execução dos Serviços', type: 'text', required: true },
      { name: 'valor_servico', label: 'Valor Total dos Serviços', type: 'currency', required: true },
      { name: 'forma_pagamento', label: 'Forma de Pagamento', type: 'select', required: true, options: ['À vista', 'Mensal', 'Quinzenal', 'Por etapa', '50% início + 50% final', 'Parcelado'] },
      { name: 'periodicidade_pagamento', label: 'Periodicidade do Pagamento', type: 'text', required: false, placeholder: 'Ex: Todo dia 5, Ao final de cada etapa' },
      { name: 'reajuste', label: 'Índice de Reajuste', type: 'select', required: false, options: ['Sem reajuste', 'IPCA', 'IGP-M', 'INPC'] },
      { name: 'materiais', label: 'Fornecimento de Materiais/Equipamentos', type: 'select', required: true, options: ['Pelo Contratante', 'Pelo Autônomo', 'Compartilhado'] },
      { name: 'confidencialidade', label: 'Cláusula de Confidencialidade', type: 'select', required: true, options: ['Sim', 'Não'] },
    ]
  },
  {
    id: 'parceria-comercial',
    title: 'Contrato de Parceria Comercial',
    description: 'Acordo de cooperação empresarial entre duas ou mais partes',
    category: 'other',
    fields: [
      { name: 'parceiro1_nome', label: 'Nome/Razão Social do Parceiro 1', type: 'text', required: true },
      { name: 'parceiro1_documento', label: 'CPF/CNPJ do Parceiro 1', type: 'text', required: true },
      { name: 'parceiro1_rg', label: 'RG do Parceiro 1 (se pessoa física)', type: 'text', required: false },
      { name: 'parceiro1_endereco', label: 'Endereço do Parceiro 1 (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'parceiro1_numero', label: 'Número', type: 'text', required: true },
      { name: 'parceiro1_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'parceiro1_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'parceiro1_estado', label: 'Estado', type: 'text', required: true },
      { name: 'parceiro1_cep', label: 'CEP', type: 'text', required: true },
      { name: 'parceiro1_email', label: 'E-mail do Parceiro 1', type: 'email', required: true },
      { name: 'parceiro1_whatsapp', label: 'WhatsApp do Parceiro 1', type: 'tel', required: true },
      { name: 'parceiro2_nome', label: 'Nome/Razão Social do Parceiro 2', type: 'text', required: true },
      { name: 'parceiro2_documento', label: 'CPF/CNPJ do Parceiro 2', type: 'text', required: true },
      { name: 'parceiro2_rg', label: 'RG do Parceiro 2 (se pessoa física)', type: 'text', required: false },
      { name: 'parceiro2_endereco', label: 'Endereço do Parceiro 2 (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'parceiro2_numero', label: 'Número', type: 'text', required: true },
      { name: 'parceiro2_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'parceiro2_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'parceiro2_estado', label: 'Estado', type: 'text', required: true },
      { name: 'parceiro2_cep', label: 'CEP', type: 'text', required: true },
      { name: 'parceiro2_email', label: 'E-mail do Parceiro 2', type: 'email', required: true },
      { name: 'parceiro2_whatsapp', label: 'WhatsApp do Parceiro 2', type: 'tel', required: true },
      { name: 'objeto_parceria', label: 'Objeto da Parceria', type: 'textarea', required: true, placeholder: 'Descreva as atividades e objetivos da parceria' },
      { name: 'finalidade_parceria', label: 'Finalidade da Parceria', type: 'textarea', required: true, placeholder: 'Qual o propósito desta parceria comercial?' },
      { name: 'contribuicao_parceiro1', label: 'Contribuição do Parceiro 1', type: 'textarea', required: true, placeholder: 'Ex: capital, know-how, estrutura, clientes' },
      { name: 'contribuicao_parceiro2', label: 'Contribuição do Parceiro 2', type: 'textarea', required: true, placeholder: 'Ex: capital, know-how, estrutura, clientes' },
      { name: 'percentual_parceiro1', label: 'Percentual de Participação do Parceiro 1 (%)', type: 'number', required: true, validation: { min: 0, max: 100 } },
      { name: 'percentual_parceiro2', label: 'Percentual de Participação do Parceiro 2 (%)', type: 'number', required: true, validation: { min: 0, max: 100 } },
      { name: 'tipo_gestao', label: 'Tipo de Gestão', type: 'select', required: true, options: ['Compartilhada entre parceiros', 'Gestão pelo Parceiro 1', 'Gestão pelo Parceiro 2', 'Gestão por administrador terceiro'] },
      { name: 'prazo_parceria', label: 'Prazo da Parceria', type: 'text', required: true, placeholder: 'Ex: 12 meses, 2 anos, indeterminado' },
      { name: 'exclusividade', label: 'Parceria Exclusiva?', type: 'select', required: true, options: ['Sim', 'Não'] },
      { name: 'territorio', label: 'Território de Atuação', type: 'text', required: false, placeholder: 'Ex: Nacional, Estado de SP, Cidade X' },
      { name: 'investimento_inicial', label: 'Investimento Inicial Total', type: 'currency', required: false },
      { name: 'divisao_custos', label: 'Divisão de Custos Operacionais', type: 'select', required: true, options: ['Proporcional à participação', '50% cada', 'Conforme natureza do custo', 'Outro'] },
      { name: 'confidencialidade', label: 'Cláusula de Confidencialidade', type: 'select', required: true, options: ['Sim', 'Não'] },
      { name: 'nao_concorrencia', label: 'Cláusula de Não Concorrência', type: 'select', required: true, options: ['Sim', 'Não'] },
    ]
  },
  {
    id: 'mandato',
    title: 'Contrato de Mandato',
    description: 'Autorização para alguém agir em nome de outra pessoa',
    category: 'other',
    fields: [
      { name: 'outorgante_nome', label: 'Nome do Outorgante (Mandante)', type: 'text', required: true },
      { name: 'outorgante_cpf', label: 'CPF do Outorgante', type: 'cpf', required: true },
      { name: 'outorgante_rg', label: 'RG do Outorgante', type: 'text', required: true },
      { name: 'outorgante_estado_civil', label: 'Estado Civil do Outorgante', type: 'select', required: true, options: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
      { name: 'outorgante_profissao', label: 'Profissão do Outorgante', type: 'text', required: true },
      { name: 'outorgante_endereco', label: 'Endereço do Outorgante (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'outorgante_numero', label: 'Número', type: 'text', required: true },
      { name: 'outorgante_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'outorgante_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'outorgante_estado', label: 'Estado', type: 'text', required: true },
      { name: 'outorgante_cep', label: 'CEP', type: 'text', required: true },
      { name: 'outorgante_email', label: 'E-mail do Outorgante', type: 'email', required: true },
      { name: 'outorgante_whatsapp', label: 'WhatsApp do Outorgante', type: 'tel', required: true },
      { name: 'outorgado_nome', label: 'Nome do Outorgado (Mandatário)', type: 'text', required: true },
      { name: 'outorgado_cpf', label: 'CPF do Outorgado', type: 'cpf', required: true },
      { name: 'outorgado_rg', label: 'RG do Outorgado', type: 'text', required: true },
      { name: 'outorgado_estado_civil', label: 'Estado Civil do Outorgado', type: 'select', required: true, options: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
      { name: 'outorgado_profissao', label: 'Profissão do Outorgado', type: 'text', required: true },
      { name: 'outorgado_endereco', label: 'Endereço do Outorgado (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'outorgado_numero', label: 'Número', type: 'text', required: true },
      { name: 'outorgado_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'outorgado_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'outorgado_estado', label: 'Estado', type: 'text', required: true },
      { name: 'outorgado_cep', label: 'CEP', type: 'text', required: true },
      { name: 'outorgado_email', label: 'E-mail do Outorgado', type: 'email', required: true },
      { name: 'outorgado_whatsapp', label: 'WhatsApp do Outorgado', type: 'tel', required: true },
      { name: 'tipo_mandato', label: 'Tipo de Mandato', type: 'select', required: true, options: ['Geral', 'Específico'] },
      { name: 'poderes_descricao', label: 'Descrição dos Poderes Outorgados', type: 'textarea', required: true, placeholder: 'Ex: Representar perante órgãos públicos, assinar contratos, movimentar contas bancárias, etc.' },
      { name: 'prazo_mandato', label: 'Prazo de Validade do Mandato', type: 'text', required: true, placeholder: 'Ex: 12 meses, 2 anos, indeterminado' },
      { name: 'remuneracao', label: 'Mandato Remunerado?', type: 'select', required: true, options: ['Não (Gratuito)', 'Sim (Oneroso)'] },
      { name: 'valor_remuneracao', label: 'Valor da Remuneração (se aplicável)', type: 'currency', required: false },
      { name: 'substabelecimento', label: 'Permite Substabelecimento?', type: 'select', required: true, options: ['Sim', 'Não'] },
      { name: 'revogacao', label: 'Cláusula de Revogação', type: 'select', required: true, options: ['Pode revogar a qualquer momento', 'Irrevogável durante o prazo'] },
      { name: 'prestacao_contas', label: 'Obrigação de Prestar Contas?', type: 'select', required: true, options: ['Sim', 'Não'] },
      { name: 'finalidade_especifica', label: 'Finalidade Específica do Mandato', type: 'textarea', required: false, placeholder: 'Descreva se há uma finalidade específica para este mandato' },
    ]
  },
  {
    id: 'alienacao-fiduciaria',
    title: 'Contrato de Alienação Fiduciária',
    description: 'Garantia de pagamento com transferência de propriedade',
    category: 'other',
    fields: [
      { name: 'credor_fiduciario_nome', label: 'Nome/Razão Social do Credor Fiduciário', type: 'text', required: true },
      { name: 'credor_fiduciario_documento', label: 'CPF/CNPJ do Credor Fiduciário', type: 'text', required: true },
      { name: 'credor_fiduciario_rg', label: 'RG do Credor Fiduciário (se pessoa física)', type: 'text', required: false },
      { name: 'credor_fiduciario_endereco', label: 'Endereço do Credor Fiduciário (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'credor_fiduciario_numero', label: 'Número', type: 'text', required: true },
      { name: 'credor_fiduciario_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'credor_fiduciario_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'credor_fiduciario_estado', label: 'Estado', type: 'text', required: true },
      { name: 'credor_fiduciario_cep', label: 'CEP', type: 'text', required: true },
      { name: 'credor_fiduciario_email', label: 'E-mail do Credor Fiduciário', type: 'email', required: true },
      { name: 'credor_fiduciario_whatsapp', label: 'WhatsApp do Credor Fiduciário', type: 'tel', required: true },
      { name: 'devedor_fiduciante_nome', label: 'Nome/Razão Social do Devedor Fiduciante', type: 'text', required: true },
      { name: 'devedor_fiduciante_documento', label: 'CPF/CNPJ do Devedor Fiduciante', type: 'text', required: true },
      { name: 'devedor_fiduciante_rg', label: 'RG do Devedor Fiduciante (se pessoa física)', type: 'text', required: false },
      { name: 'devedor_fiduciante_estado_civil', label: 'Estado Civil do Devedor Fiduciante', type: 'select', required: true, options: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'União Estável'] },
      { name: 'devedor_fiduciante_profissao', label: 'Profissão do Devedor Fiduciante', type: 'text', required: true },
      { name: 'devedor_fiduciante_endereco', label: 'Endereço do Devedor Fiduciante (Rua/Av/Rod)', type: 'text', required: true },
      { name: 'devedor_fiduciante_numero', label: 'Número', type: 'text', required: true },
      { name: 'devedor_fiduciante_bairro', label: 'Bairro', type: 'text', required: true },
      { name: 'devedor_fiduciante_cidade', label: 'Cidade', type: 'text', required: true },
      { name: 'devedor_fiduciante_estado', label: 'Estado', type: 'text', required: true },
      { name: 'devedor_fiduciante_cep', label: 'CEP', type: 'text', required: true },
      { name: 'devedor_fiduciante_email', label: 'E-mail do Devedor Fiduciante', type: 'email', required: true },
      { name: 'devedor_fiduciante_whatsapp', label: 'WhatsApp do Devedor Fiduciante', type: 'tel', required: true },
      { name: 'tipo_bem', label: 'Tipo do Bem Alienado', type: 'select', required: true, options: ['Veículo Automotor', 'Imóvel', 'Máquinas/Equipamentos', 'Outro'] },
      { name: 'bem_descricao', label: 'Descrição Completa do Bem', type: 'textarea', required: true, placeholder: 'Descreva detalhadamente o bem objeto da alienação fiduciária' },
      { name: 'veiculo_placa', label: 'Placa do Veículo (se aplicável)', type: 'text', required: false },
      { name: 'veiculo_chassi', label: 'Chassi do Veículo (se aplicável)', type: 'text', required: false },
      { name: 'veiculo_renavam', label: 'RENAVAM (se aplicável)', type: 'text', required: false },
      { name: 'imovel_matricula', label: 'Matrícula do Imóvel (se aplicável)', type: 'text', required: false },
      { name: 'imovel_cartorio', label: 'Cartório de Registro (se aplicável)', type: 'text', required: false },
      { name: 'valor_bem', label: 'Valor do Bem Alienado', type: 'currency', required: true },
      { name: 'valor_financiado', label: 'Valor Total Financiado', type: 'currency', required: true },
      { name: 'valor_entrada', label: 'Valor da Entrada', type: 'currency', required: false },
      { name: 'numero_parcelas', label: 'Número de Parcelas', type: 'number', required: true, validation: { min: 1, max: 120 } },
      { name: 'valor_parcela', label: 'Valor de Cada Parcela', type: 'currency', required: true },
      { name: 'taxa_juros', label: 'Taxa de Juros Mensal (%)', type: 'number', required: true, validation: { min: 0, max: 10 } },
      { name: 'vencimento_primeira_parcela', label: 'Vencimento da Primeira Parcela', type: 'date', required: true },
      { name: 'local_pagamento', label: 'Local/Forma de Pagamento', type: 'text', required: true, placeholder: 'Ex: Boleto bancário, débito em conta' },
      { name: 'cet', label: 'Custo Efetivo Total - CET (%)', type: 'number', required: true },
      { name: 'seguro_obrigatorio', label: 'Seguro Obrigatório do Bem?', type: 'select', required: true, options: ['Sim', 'Não'] },
      { name: 'multa_inadimplencia', label: 'Multa por Inadimplência (%)', type: 'number', required: true, validation: { min: 0, max: 10 } },
      { name: 'mora_diaria', label: 'Juros de Mora ao Dia (%)', type: 'number', required: true, validation: { min: 0, max: 1 } },
      { name: 'vencimento_antecipado', label: 'Cláusula de Vencimento Antecipado', type: 'select', required: true, options: ['Sim', 'Não'] },
      { name: 'consolidacao_propriedade', label: 'Procedimento de Consolidação da Propriedade', type: 'select', required: true, options: ['Conforme Código Civil', 'Busca e Apreensão (DL 911/69)'] },
    ]
  }
];